# docker-compose.override.yml (For local testing ONLY)
services:
  nsdc-website:
    ports:
      - "8080:80"
    environment:
      - RENDER_DEPLOY_HOOK_URL=${RENDER_DEPLOY_HOOK_URL}
      - MOCK_HERO_URL=${MOCK_HERO_URL}
      - MOCK_ANNOUNCEMENTS_URL=${MOCK_ANNOUNCEMENTS_URL}
      - MOCK_ABOUT_URL=${MOCK_ABOUT_URL}
      - MOCK_EVENTS_URL=${MOCK_EVENTS_URL}
      - MOCK_PROJECTS_URL=${MOCK_PROJECTS_URL}
      - MOCK_RESOURCES_URL=${MOCK_RESOURCES_URL}
      - MOCK_TEAMS_URL=${MOCK_TEAMS_URL}
      - MOCK_TEAM_PREVIEW_URL=${MOCK_TEAM_PREVIEW_URL}
      - MOCK_LINKS_URL=${MOCK_LINKS_URL}
