services:
  nsdc-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: nsdc-site:local
    container_name: nsdc-site-local
    restart: unless-stopped

    ports:
      - "4321:4321"

    env_file:
      - .env

    networks:
      - default
